name = "talebearer"
main = "src/server/index.ts"
compatibility_date = "2023-11-01"
compatibility_flags = [ "nodejs_compat" ]
[[d1_databases]]
binding = "DB"
database_name = "talebearer"
database_id = "3d04bebc-39ff-497a-bdbf-1c47ca8ce1d6"